import type { TardsCategory, TardsNode } from './types'

/*
  ============================================================
  CENTRALIZED RESOURCE CONFIGURATION
  ------------------------------------------------------------
  Edit this file to change the DEFAULT nodes + categories.
  Anything you add / edit / favorite in the live UI is stored
  in localStorage and layered on top of these defaults.
  Use the "RESET NETWORK" action (Settings) to return here.
  ============================================================
*/

export const DEFAULT_CATEGORIES: TardsCategory[] = [
  { id: 'ai', label: 'AI', icon: 'BrainCircuit' },
  { id: 'coding', label: 'Coding', icon: 'Code2' },
  { id: 'cyber', label: 'Cyber', icon: 'ShieldHalf' },
  { id: 'learning', label: 'Learning', icon: 'GraduationCap' },
  { id: 'tools', label: 'Tools', icon: 'Wrench' },
  { id: 'tutorials', label: 'Tutorials', icon: 'BookOpen' },
  { id: 'methods', label: 'Methods', icon: 'FlaskConical' },
  { id: 'projects', label: 'Projects', icon: 'FolderGit2' },
  { id: 'other', label: 'Other', icon: 'Boxes' },
]

let seq = 0
const n = (
  node: Omit<TardsNode, 'id' | 'createdAt' | 'order'> & Partial<Pick<TardsNode, 'id'>>,
): TardsNode => ({
  id: node.id ?? `node-${(++seq).toString().padStart(3, '0')}`,
  createdAt: Date.now() - (200 - seq) * 3600_000,
  order: seq,
  ...node,
})

export const DEFAULT_NODES: TardsNode[] = [
  n({
    title: 'Gemini',
    description: 'Advanced AI research assistant and multimodal reasoning terminal.',
    url: 'https://gemini.google.com',
    category: 'ai',
    icon: 'Sparkles',
    status: 'ONLINE',
    featured: true,
    badge: 'CORE',
    shortcut: 'G',
  }),
  n({
    title: 'ChatGPT',
    description: 'Conversational intelligence node for drafting, code, and analysis.',
    url: 'https://chat.openai.com',
    category: 'ai',
    icon: 'MessageSquareCode',
    status: 'ONLINE',
    featured: false,
    shortcut: 'C',
  }),
  n({
    title: 'Claude',
    description: 'Long-context reasoning engine for research and document synthesis.',
    url: 'https://claude.ai',
    category: 'ai',
    icon: 'Bot',
    status: 'ONLINE',
    featured: false,
  }),
  n({
    title: 'v0',
    description: 'Generative UI engineering node. Ships production interfaces from prompts.',
    url: 'https://v0.app',
    category: 'ai',
    icon: 'Wand2',
    status: 'ONLINE',
    featured: true,
    badge: 'PRIORITY',
  }),
  n({
    title: 'GitHub',
    description: 'Primary source-control mesh. Repositories, actions, and deployment hooks.',
    url: 'https://github.com',
    category: 'coding',
    icon: 'Github',
    status: 'SECURE',
    featured: false,
    shortcut: 'H',
  }),
  n({
    title: 'VS Code Web',
    description: 'Remote development terminal. Edit repositories directly in-browser.',
    url: 'https://vscode.dev',
    category: 'coding',
    icon: 'Code2',
    status: 'ONLINE',
    featured: false,
  }),
  n({
    title: 'CodePen',
    description: 'Front-end fabrication sandbox for rapid interface prototypes.',
    url: 'https://codepen.io',
    category: 'coding',
    icon: 'Codepen',
    status: 'ONLINE',
    featured: false,
  }),
  n({
    title: 'HackTheBox',
    description: 'Offensive security proving grounds. Live penetration-testing labs.',
    url: 'https://www.hackthebox.com',
    category: 'cyber',
    icon: 'ShieldHalf',
    status: 'CLASSIFIED',
    featured: false,
    badge: 'RESTRICTED',
  }),
  n({
    title: 'TryHackMe',
    description: 'Guided cyber-defense training modules and attack simulations.',
    url: 'https://tryhackme.com',
    category: 'cyber',
    icon: 'Bug',
    status: 'SECURE',
    featured: false,
  }),
  n({
    title: 'Shodan',
    description: 'Reconnaissance grid. Search engine for exposed internet-facing devices.',
    url: 'https://www.shodan.io',
    category: 'cyber',
    icon: 'Radar',
    status: 'CLASSIFIED',
    featured: false,
  }),
  n({
    title: 'MDN Web Docs',
    description: 'Authoritative web platform documentation archive.',
    url: 'https://developer.mozilla.org',
    category: 'learning',
    icon: 'BookOpen',
    status: 'ONLINE',
    featured: false,
  }),
  n({
    title: 'freeCodeCamp',
    description: 'Structured curriculum node. Full-stack certification tracks.',
    url: 'https://www.freecodecamp.org',
    category: 'learning',
    icon: 'GraduationCap',
    status: 'ONLINE',
    featured: false,
  }),
  n({
    title: 'Excalidraw',
    description: 'Schematic drawing surface for architecture and system diagrams.',
    url: 'https://excalidraw.com',
    category: 'tools',
    icon: 'PenTool',
    status: 'ONLINE',
    featured: false,
  }),
  n({
    title: 'Vercel',
    description: 'Deployment mainframe. Ship frontends and edge functions globally.',
    url: 'https://vercel.com',
    category: 'tools',
    icon: 'Triangle',
    status: 'ONLINE',
    featured: false,
    shortcut: 'V',
  }),
  n({
    title: 'Figma',
    description: 'Collaborative interface design node with live component systems.',
    url: 'https://figma.com',
    category: 'tools',
    icon: 'Figma',
    status: 'ONLINE',
    featured: false,
  }),
  n({
    title: 'Regex101',
    description: 'Pattern-matching analyzer. Build and debug regular expressions live.',
    url: 'https://regex101.com',
    category: 'tools',
    icon: 'Regex',
    status: 'ONLINE',
    featured: false,
  }),
  n({
    title: 'The Odin Project',
    description: 'Open-source full-stack curriculum with project-based methods.',
    url: 'https://www.theodinproject.com',
    category: 'tutorials',
    icon: 'Map',
    status: 'ONLINE',
    featured: false,
  }),
  n({
    title: 'roadmap.sh',
    description: 'Developer skill-tree methods and guided progression paths.',
    url: 'https://roadmap.sh',
    category: 'methods',
    icon: 'Route',
    status: 'ONLINE',
    featured: false,
  }),
  n({
    title: 'Awesome Lists',
    description: 'Curated index of high-signal resource collections across domains.',
    url: 'https://github.com/sindresorhus/awesome',
    category: 'projects',
    icon: 'Star',
    status: 'ONLINE',
    featured: false,
  }),
  n({
    title: 'Hacker News',
    description: 'Signal feed for engineering, security, and frontier technology.',
    url: 'https://news.ycombinator.com',
    category: 'other',
    icon: 'Newspaper',
    status: 'ONLINE',
    featured: false,
  }),
]
